chore: bump h2o version to 3.46.0.11 (#153)
Bumps h2o version to `3.46.0.11` to fix multiple CVEs (CVE-2023-6016, CVE-2023-6038, CVE-2024-10553, CVE-2024-45758, CVE-2024-5986, CVE-2025-5662, CVE-2025-6507).

The bump required adding a fallback mechanism to find the default value of missing API descriptors when upgrading schema bindings. Starting in  `3.40.0.1`, some choice/enum fields were not being initialized with default constants, causing the reflection lookup to return null and failing to statically initialize the core `H2OAlgorithm` registry. This triggered a `ExceptionInInitializerError` during class loading, resulting in a cascade of `NoClassDefFoundError` failures across loading and training test suites when processing uninitialized choice descriptors, so we added a logic of case-insensitive matching with fallback to handle these uninitialized or mismatched enum descriptors.

Also, it required explicitly filtering out regression influence diagnostics (`influence`) as it these can only be specified for gaussian and binomial families (these were introduced in `3.40.0.1` - see https://github.com/h2oai/h2o-3/blob/master/Changes.md#kurka-34001---282023)

Additionally, the MR fixes an issue with `non_negative` constraints in GLM, as these are not allowed for multi-classification datasets (since `3.36.1.1` GLM init fails fast if this is misconfigured - see https://github.com/h2oai/h2o-3/blob/master/Changes.md#zumbo-33611---4132022).